### ISSUE TITLE
Mapping of metadataStandardName

### ISSUE THREAD

**Issue by uvoges** [SEMICeu/GeoDCAT-AP#128]
The metadata standard as defined in ISO 19115 XPath:
`gmd:MD_Metadata/gmd:metadataStandardName/gco:CharacterString`
`gmd:MD_Metadata/gmd:metadataStandardVersion/gco:CharacterString`

has to be mapped to GeoDCAT-AP, e.g. in a `dct:confomsTo`
A vocabulary is needed to which metadata standard of metadata can be conform to…

Currently mapped to something like:
foaf:isPrimaryTopicOf/rdf:Description/dct:source/dct:conformsTo	Metadata Standard
```xml
<dct:source rdf:parseType="Resource">
    <cnt:characterEncoding rdf:datatype="http://www.w3.org/2001/XMLSchema#string">UTF-8</cnt:characterEncoding>
    <dct:conformsTo rdf:parseType="Resource">
        <dct:title xml:lang="de">INSPIRE Metadata Implementing Rules: Technical Guidelines based on EN ISO 19115 and EN ISO 19119</dct:title>
        <owl:versionInfo xml:lang="de">V. 1.2</owl:versionInfo>
    </dct:conformsTo>
```

**Comment by jakubklimek** [comment]
@uvoges since this is mapped in `dct:conformsTo` already, do you suggest to create a new controlled vocabulary for the various standards used in INSPIRE?
As far as I understand, any standard can be currently named like this in the INSPIRE metadata and there is no such controlled vocabulary / list of usable standards.
