### ISSUE TITLE
Little information rethrieved by XSLT from keywords in Anchor form

### ISSUE THREAD

**Issue by hallinpihlatie** [SEMICeu/GeoDCAT-AP#134]
Hi,

I've played around with the https://geodcat-ap.semic.eu/api/ a bit. 

If I have a key word as Anchor it rethrieves only the URL of the Anchor e.g. http://data.europa.eu/bna/c_ac64a52d, not the keyword itself. I'm wondering this is the intention. I'd personally prefer that at least the actual value or concept also would rethrieved, eg. Geospatial, in addition to the URL for example to have it available directly on a html page. As also the vocabulary name indicates that it is a High-value dataset key word, which is information that also be included and useful.

[Link to ISO metadata of a service](https://www.paikkatietohakemisto.fi/geonetwork/srv/fin/catalog.search#/metadata/44204afc-9951-4c25-ab18-646afd78a89a)
The RDF-file is attached as a zip file below.

ISO:
```xml
<gmd:keyword>
    <gmx:Anchor xlink:href="http://data.europa.eu/bna/c_ac64a52d">Geospatial</gmx:Anchor>
</gmd:keyword>
<gmd:type>
    <gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme"/>
</gmd:type>
<gmd:thesaurusName>
    <gmd:CI_Citation>
        <gmd:title>
            <gmx:Anchor xlink:href="http://data.europa.eu/bna/asd487ae75">High-value dataset categories</gmx:Anchor>
        </gmd:title>
        <gmd:date>
            <gmd:CI_Date>
                <gmd:date>
                    <gco:Date>2023-09-27</gco:Date>
                </gmd:date>
                <gmd:dateType>
                    <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication"/>
                </gmd:dateType>
            </gmd:CI_Date>
        </gmd:date>
```
**->**
GeoDCAT-AP:
```xml
    <dcat:theme rdf:resource="http://data.europa.eu/bna/c_ac64a52d"/>
```

[example.zip](https://github.com/user-attachments/files/16908783/example.zip)

**Comment by jakubklimek** [comment]
This is currently the expected behavior (also in DCAT-AP itself), as GeoDCAT-AP is based on Linked Data principles, and when a URL is provided for a theme (keyword), that alone is enough to represent the concept, and it is expected that it can be dereferenced (accessed) if more information is requested.

This is also related to https://github.com/SEMICeu/GeoDCAT-AP/issues/111 dealing with how much of the external information should be embedded.

A separate issue specific to this case is that in the case of an HVD category, it should be mapped to the [HVD Category (`r5r:hvdCategory`)](https://semiceu.github.io/DCAT-AP/releases/3.0.0-hvd/#Dataset.HVDCategory) property from DCAT-AP HVD rather than the `dcat:theme` property. But for this, the XSLT needs to be adjusted by the provider, as as far as we know, the mentioned pattern of identifying HVD categories in INSPIRE metadata is not (yet?) standardized, and is therefore provider-specific.

**Comment by jescriu** [comment]
https://github.com/INSPIRE-MIF/GeoDCAT-AP-pilot/issues/2

> FYI, this GitHub issue:
> https://github.com/SEMICeu/GeoDCAT-AP/issues/134 (the issue was closed waiting for a common way in INSPIRE XML to tag HVDs)

Should anything in this thread be revisited now that the geospatial HVD tagging good practice has been agreed and implemented in the SEMIC XSLT?
