### ISSUE TITLE
INSPIRE and ISO 19115 Mappings - Revisions to be done

### ISSUE THREAD

**Issue by AntoRot** [SEMICeu/GeoDCAT-AP#24]
Section [B.4.1 Overview of bindings for GeoDCAT-AP Core](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#overview-of-bindings-for-geodcat-ap-core): add also ```dcat:DataService``` as domain for the property ```dct:title```;

Section [B.6.4 Resource locator - *On-line resource](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#resource-locator---on-line-resource): the property mapped to the value "download" in ISO 19115 – CI_OnlineFunctionCode should be ```dcat:downloadURL```;

Section [B.6.4 Resource locator - *On-line resource](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#resource-locator---on-line-resource): concerning the service protocol, the URIs referenced in the [INSPIRE register "Protocol values"](https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue) should be used.

**Comment by andrea-perego** [comment]
@AntoRot said:

> Section [B.4.1 Overview of bindings for GeoDCAT-AP Core](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#overview-of-bindings-for-geodcat-ap-core): add also `dcat:DataService` as domain for the property `dct:title`;

Proposed revision included in pull request https://github.com/SEMICeu/GeoDCAT-AP/pull/27

> Section [B.6.4 Resource locator - *On-line resource](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#resource-locator---on-line-resource): the property mapped to the value "download" in ISO 19115 – CI_OnlineFunctionCode should be `dcat:downloadURL`;

This mapping is the same one used in the previous versions of GeoDCAT-AP.

The reason for mapping it to `dcat:accessURL` instead of `dcat:downloadURL` is that there is no safe way to detect whether the URL points directly to a file to be downloaded or to a download page.

Unless there is evidence that the situation has changed, I would suggest we keep this mapping.

> Section [B.6.4 Resource locator - *On-line resource](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#resource-locator---on-line-resource): concerning the service protocol, the URIs referenced in the [INSPIRE register "Protocol values"](https://inspire.ec.europa.eu/metadata-codelist/ProtocolValue) should be used.

Proposed revision included in pull request https://github.com/SEMICeu/GeoDCAT-AP/pull/27

@AntoRot , are you happy with these proposals?

**Comment by AntoRot** [comment]
Thanks @andrea-perego.

Your proposals are fine to me.

**Comment by andrea-perego** [comment]
Revision implemented in the editor's draft in view of the publication of the 2nd working draft:

https://semiceu.github.io/GeoDCAT-AP/drafts/latest/
