### ISSUE TITLE
Dataset class - lack of licence and access rights propreties

### ISSUE THREAD

**Issue by bfrichet3** [SEMICeu/GeoDCAT-AP#65]
Dear,

I hope you are all fine.

I have a question about two unexisting propreties of the Dataset class. As you know, on the one hand licence and access rights propretries are not listed as recommanded or optional propreties of the Dataset class.  On the other hand there are listed as recommande/optional propreties of the Distribution class.

At the federal belgian administration we are very interested by creating and publishing (geo)DCAT AP files by using original INSPIRE/ISO  metadata records: it is our paradigm to use XML content and to follow INSPIRE/ISO ways of assambling metadata. The European Regulation 1205/2008 states that Limitations on public access (mapped to GeoDCAT AP access right) and Conditions for access and use (mapped to GeoDCAT AP licence) characterize the datasets (and not the particular files that one can download).

Furthermore, I cannot see the meaning of different licences or use limitations for different "phyical embodiments" of the same dataset in different formats to reuse the terms of the Distribution's definition.

So my question is: what were the specific reasons to exclude these two propreties from Dataset and to add them in the Distribution class: access rigjhts is even included in the DCAT AP profile as optional proprety so I can assume that there was a purpose to that choice.

Regards,

![image](https://user-images.githubusercontent.com/80756452/136986651-24f36a07-e2ba-442f-9f19-09413af917e3.png)

**Comment by bertvannuffelen** [comment]
The history of the legal information (in particular the licence information) is based in the situation of DCAT 1.0 (DCAT-AP 1.x).

At that time solely Dataset and Distribution existed. The WG identified that for each kind of distribution there are different legal clauses (a file is different than a REST service, or a picture). In order to ensure that legal information was unambiguous and no interpretation had to be made like if you use this distribution than you should comply to the distribution statement + the dataset statement, the decision was made to connect legal information with the concrete representation of the dataset. 

The consequence is that for cases where the legal information holds for all distributions this has to be spread over all distributions. In the practice, this is so problematic as it seems because most publishers have a nice webpage to which one references. 

Because there were no voices to change this view, this practice has been continued in DCAT-AP 2.x, even though DCAT 2.x allows to specify it at the level of Dataset. Good reading material is https://w3c.github.io/dxwg/dcat/#license-rights.
 
In the practice we see that very few publishers are adding more complex statements in machine readable form, which is nowadays supported by DCAT(-AP). So this area, even though it is important for reuse, seems in the practice mostly fine with a link to a (licence) document listing all the legal clauses. I know that the GeoSpatial community has practice to add some "clauses" in the metadata.  Following the W3C guidelines and the above guideline to connect them with the concrete data representation they will become dct:rights statements. 

In addition there is dct:accessRights that will allow to indicate if the catalogued resource is intended for public or non-public data sharing.

**Comment by bfrichet3** [comment]
Dear @bertvannuffelen 

To use all the benefits of the Object-oriented Modelisation, wouldn't that be interesting to use licence and access rights at the level of the dataset _unless there are differences between the paritcular physical files concerning the licences/access rights_ ?

I mean, why should we repeat one single informations many times if it's possible to deduce that information by inheritence from an upper class?

Regards,

**Comment by bertvannuffelen** [comment]
Hi @bfrichet3,

There is a semantical difference between Dataset and Distribution. A Dataset is a conceptual collection of data points, while a Distribution is a concrete representation (in some format) of the dataset. So there is no notion of inheritence between then.

Properties at the level of Dataset are generic and applicable to the Dataset as whole, in particular to all its distributions. 
As explained, in the past, the community identified that there are substantial differences from one distribution form to another and that this also is visible often as differences in legal information.

If the community wants to accept legal information at dataset level then the community should determine what the meaning of the following cases are:

```
_:dataset1 a dcat:Dataset.
_:dataset1 dcat:distribution _:dist1.
_:dataset1 dct:license url1.

_:dataset2 a dcat:Dataset.
_:dataset2 dcat:distribution _:dist2.
_:dist2 dct:license url2.

_:dataset3 a dcat:Dataset.
_:dataset3 dcat:distribution _:dist3.
_:dataset3 dct:license url3a.
_:dist3 dct:license url3b.
``` 
In particular the third case is difficult: shoudl url3b be an extended document of url3a? Can it contradict each other? Should they be the same? Or do are any implications left for the implementor/publisher/reuser to do? I am open to many interpretations but it should be clear which one to pick.

As a side-effect currently license information is recommended, should it also be at the level of Dataset?  

This kind of discussion is common for any property that is shared between dataset and distribution. But for title and distribution the impact is limited, but for legal information it is. As such there is no issue to endorse more properties, but in this case I believe we best have it accompanied with a good usage guideline because otherwise all possible cases will emerge, and we come back to the need for a usage guideline. If you can contribute to that then we can see if this forms a basis for a resolution that the community supports.

**Comment by jakubklimek** [comment]
The issue has been clearly answered and explained by @bertvannuffelen . It is an outcome of a discussion at the level of DCAT (see [distribution license usage note](https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_license)), adopted by DCAT-AP. Since GeoDCAT-AP in a DCAT-AP subprofile, it complies with that approach. Since there are no further comments on this, I propose to close this issue.

@bfrichet3 if you want to discuss this further, please do so in the [DCAT repository](https://github.com/w3c/dxwg/issues), from where the approach in question originates.
